#!/usr/bin/env python3
"""
Yash Study Hub - SAFE MODE (used automatically by the GitHub build workflow).

The workflow first builds the FULL app. If that build fails, it runs this
script and builds again, so you still get a working APK. Safe mode switches
off only the add-ons that are new/risky for the build:

  1. the in-app PDF viewer (needs the `webview_flutter` plugin) - PDFs then
     open in the browser / Drive app, exactly like before;
  2. the Firebase google-services Gradle plugin (push notifications when the
     app is closed) - notifications still work while the app is open.

Everything else stays the same. Run from the flutter-app folder:

    python3 tools/safe_mode.py .
"""
import os
import re
import sys

STUB = """import 'package:flutter/material.dart';
import '../utils/open_link.dart';

// SAFE MODE (generated by tools/safe_mode.py because the full build failed):
// the in-app PDF viewer is switched off, PDFs open in the browser / Drive app.
Future<void> openPdfInApp(
  BuildContext context, {
  required String link,
  required String title,
  bool allowExternalOpen = true,
}) async {
  await openExternalLink(context, link);
}
"""


def read(path):
    with open(path, encoding="utf-8") as f:
        return f.read()


def write(path, text):
    with open(path, "w", encoding="utf-8") as f:
        f.write(text)


def main():
    root = os.path.abspath(sys.argv[1]) if len(sys.argv) > 1 else os.getcwd()
    report = []

    # 1) in-app PDF viewer off
    pubspec = os.path.join(root, "pubspec.yaml")
    if os.path.isfile(pubspec):
        text = read(pubspec)
        new, n = re.subn(r"(?m)^[ \t]*webview_flutter:.*\n", "", text)
        if n:
            write(pubspec, new)
        report.append("webview_flutter removed from pubspec.yaml" if n else "webview_flutter was not in pubspec.yaml")
    viewer = os.path.join(root, "lib", "screens", "pdf_viewer_screen.dart")
    if os.path.isfile(viewer):
        write(viewer, STUB)
        report.append("pdf_viewer_screen.dart replaced with a small 'open outside' version")

    # 2) google-services plugin off
    android = os.path.join(root, "android")
    removed = 0
    for rel in ("settings.gradle", "settings.gradle.kts", os.path.join("app", "build.gradle"), os.path.join("app", "build.gradle.kts")):
        path = os.path.join(android, rel)
        if os.path.isfile(path):
            text = read(path)
            new = "\n".join(line for line in text.split("\n") if "com.google.gms.google-services" not in line)
            if new != text:
                write(path, new)
                removed += 1
    json_path = os.path.join(android, "app", "google-services.json")
    if os.path.isfile(json_path):
        os.remove(json_path)
        removed += 1
    report.append("google-services plugin/file removed (%d changes)" % removed)

    print("SAFE MODE applied:")
    for line in report:
        print("  - " + line)
    return 0


if __name__ == "__main__":
    sys.exit(main())
